spring.datasource.url=jdbc:mysql://localhost:3306/encurtador?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Tim@o2007r

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true